     1	import js from '@eslint/js';
     2	import prettier from 'eslint-config-prettier/flat';
     3	
     4	export default [
     5	  {
     6	    ignores: [
     7	      'node_modules/**',
     8	      'client/dist/**',
     9	      'client/js/bootstrap.bundle.min.js',
    10	      'data/**',
    11	      'backups/**',
    12	      'scraped_decoded/**',
    13	      'sor/**',
    14	      'check/**',
    15	      'client/js/modules/auth-profile.js',
    16	    ],
    17	  },
    18	  js.configs.recommended,
    19	  prettier,
    20	  {
    21	    files: ['src/**/*.js'],
    22	    languageOptions: {
    23	      ecmaVersion: 2022,
    24	      sourceType: 'commonjs',
    25	      globals: {
    26	        // Node globals
    27	        require: 'readonly',
    28	        module: 'readonly',
    29	        exports: 'readonly',
    30	        process: 'readonly',
    31	        __dirname: 'readonly',
    32	        __filename: 'readonly',
    33	        Buffer: 'readonly',
    34	        setTimeout: 'readonly',
    35	        clearTimeout: 'readonly',
    36	        setInterval: 'readonly',
    37	        clearInterval: 'readonly',
    38	        console: 'readonly',
    39	        global: 'readonly',
    40	      },
    41	    },
    42	    rules: {
    43	      // Legacy codebase uses `var` throughout; migrate file-by-file to
    44	      // const/let as each file is touched (PROMPT 7 — no full rewrite).
    45	      'no-var': 'warn',
    46	      'prefer-const': 'warn',
    47	      'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_' }],
    48	      'no-console': 'off',
    49	      'no-empty': 'warn',
    50	      'no-useless-catch': 'warn',
    51	      // Legacy: redeclared `var` and write-then-ignore assignments are symptoms
    52	      // of the old style; surfaced as warnings so the var->const/let migration
    53	      // (PROMPT 7) addresses them file-by-file without a full rewrite.
    54	      'no-redeclare': 'warn',
    55	      'no-useless-assignment': 'warn',
    56	    },
    57	  },
    58	  {
    59	    files: ['client/js/**/*.js'],
    60	    languageOptions: {
    61	      ecmaVersion: 2022,
    62	      sourceType: 'module',
    63	      globals: {
    64	        window: 'readonly',
    65	        document: 'readonly',
    66	        navigator: 'readonly',
    67	        localStorage: 'readonly',
    68	        sessionStorage: 'readonly',
    69	        console: 'readonly',
    70	        setTimeout: 'readonly',
    71	        clearTimeout: 'readonly',
    72	        setInterval: 'readonly',
    73	        clearInterval: 'readonly',
    74	        location: 'readonly',
    75	        history: 'readonly',
    76	        fetch: 'readonly',
    77	        FormData: 'readonly',
    78	        FileReader: 'readonly',
    79	        Blob: 'readonly',
    80	        URL: 'readonly',
    81	        URLSearchParams: 'readonly',
    82	        Audio: 'readonly',
    83	        RTCPeerConnection: 'readonly',
    84	        RTCSessionDescription: 'readonly',
    85	        RTCIceCandidate: 'readonly',
    86	        MediaStream: 'readonly',
    87	        getUserMedia: 'readonly',
    88	        MutationObserver: 'readonly',
    89	        requestAnimationFrame: 'readonly',
    90	        cancelAnimationFrame: 'readonly',
    91	        matchMedia: 'readonly',
    92	        DOMParser: 'readonly',
    93	        CSS: 'readonly',
    94	        screen: 'readonly',
    95	        Event: 'readonly',
    96	        CustomEvent: 'readonly',
    97	        innerWidth: 'readonly',
    98	        innerHeight: 'readonly',
    99	        addEventListener: 'readonly',
   100	        removeEventListener: 'readonly',
   101	        prompt: 'readonly',
   102	        alert: 'readonly',
   103	        confirm: 'readonly',
   104	        atob: 'readonly',
   105	        btoa: 'readonly',
   106	        encodeURIComponent: 'readonly',
   107	        decodeURIComponent: 'readonly',
   108	        XMLHttpRequest: 'readonly',
   109	        CustomEvent: 'readonly',
   110	        // Browser libs loaded as classic scripts
   111	        bootstrap: 'readonly',
   112	        io: 'readonly',
   113	        PNotify: 'readonly',
   114	        Swal: 'readonly',
   115	        $: 'readonly',
   116	        jQuery: 'readonly',
   117	      },
   118	    },
   119	    rules: {
   120	      'no-var': 'warn',
   121	      'prefer-const': 'warn',
   122	      'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_' }],
   123	      'no-console': 'off',
   124	      'no-empty': 'warn',
   125	      'no-useless-catch': 'warn',
   126	      'no-restricted-globals': 'off',
   127	      'no-redeclare': 'warn',
   128	      'no-useless-assignment': 'warn',
   129	    },
   130	  },
   131	  {
   132	    files: ['scripts/**/*.cjs'],
   133	    languageOptions: {
   134	      ecmaVersion: 2022,
   135	      sourceType: 'commonjs',
   136	      globals: {
   137	        require: 'readonly',
   138	        module: 'readonly',
   139	        exports: 'readonly',
   140	        process: 'readonly',
   141	        __dirname: 'readonly',
   142	        __filename: 'readonly',
   143	        Buffer: 'readonly',
   144	        setTimeout: 'readonly',
   145	        clearTimeout: 'readonly',
   146	        setInterval: 'readonly',
   147	        clearInterval: 'readonly',
   148	        console: 'readonly',
   149	        global: 'readonly',
   150	      },
   151	    },
   152	    rules: {
   153	      'no-var': 'warn',
   154	      'prefer-const': 'warn',
   155	      'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_' }],
   156	      'no-empty': 'warn',
   157	    },
   158	  },
   159	  {
   160	    files: ['test/**/*.js'],
   161	    languageOptions: {
   162	      ecmaVersion: 2022,
   163	      sourceType: 'commonjs',
   164	      globals: {
   165	        require: 'readonly',
   166	        module: 'readonly',
   167	        exports: 'readonly',
   168	        process: 'readonly',
   169	        __dirname: 'readonly',
   170	        __filename: 'readonly',
   171	        Buffer: 'readonly',
   172	        setTimeout: 'readonly',
   173	        clearTimeout: 'readonly',
   174	        setInterval: 'readonly',
   175	        clearInterval: 'readonly',
   176	        console: 'readonly',
   177	        // Vitest globals
   178	        describe: 'readonly',
   179	        it: 'readonly',
   180	        test: 'readonly',
   181	        expect: 'readonly',
   182	        beforeEach: 'readonly',
   183	        afterEach: 'readonly',
   184	        beforeAll: 'readonly',
   185	        afterAll: 'readonly',
   186	        vi: 'readonly',
   187	      },
   188	    },
   189	    rules: {
   190	      'no-var': 'warn',
   191	      'prefer-const': 'warn',
   192	      'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_' }],
   193	      'no-empty': 'warn',
   194	      'no-useless-catch': 'warn',
   195	    },
   196	  },
   197	];
   198	